[package]
name = "calia"
version.workspace = true
edition.workspace = true

[dependencies]
calia-macro.workspace = true
cgp.workspace = true

[dev-dependencies]
calia-sqlx.workspace = true
calia-postgresql.workspace = true